#!/bin/bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
THEME_DIR="$HOME/.config/sketchybar/themes"
FONT="Maple Mono NF"

##### Load Catppuccin theme (change filename to switch flavour) #####
# Available: catppuccin-mocha.sh | catppuccin-macchiato.sh | catppuccin-frappe.sh | catppuccin-latte.sh
source "$THEME_DIR/catppuccin-latte.sh"
source "$THEME_DIR/helpers.sh"

##### Bar Appearance #####
sketchybar --bar \
  height=32 \
  position=top \
  topmost=window \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  color=$(c "$BASE") \
  border_width=1 \
  border_color=$(c "$SURFACE1") \
  blur_radius=0 \
  shadow=off

##### Defaults #####
sketchybar --default \
  updates=when_shown \
  icon.font="$FONT:Regular:13.0" \
  icon.color=$(c "$TEXT") \
  label.font="$FONT:Regular:13.0" \
  label.color=$(c "$TEXT") \
  padding_left=4 \
  padding_right=4

##### Left: AeroSpace Workspaces #####
sketchybar --add event aerospace_workspace_change

WORKSPACES=("1-Work" "2-work++" "3-work#" "4-schedule" "5-browser" "6" "7" "8" "9-chat" "A")

for ws in "${WORKSPACES[@]}"; do
  sid=$(echo "$ws" | tr '#+' '__')
  sketchybar \
    --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
      label="$ws" \
      label.padding_left=8 \
      label.padding_right=8 \
      background.height=22 \
      background.corner_radius=4 \
      background.drawing=off \
      background.color=$(c "$BLUE") \
      label.color=$(c "$SUBTEXT1") \
      click_script="aerospace workspace \"$ws\"" \
      script="bash $PLUGIN_DIR/aerospace.sh \"$ws\""
done

##### Right: Date + Clock #####
sketchybar --add item clock right \
  --set clock \
    update_freq=10 \
    icon=󰃰 \
    icon.padding_right=4 \
    icon.color=$(c "$LAVENDER") \
    label.color=$(c "$TEXT") \
    script="sketchybar --set \$NAME label=\"\$(date '+%a %d %b  %H:%M')\""

##### Initialize #####
sketchybar --update
